{{- if .Values.minio.enabled }}
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ include "dgsn-infra.fullname" . }}-minio
  labels:
    {{- include "dgsn-infra.labels" . | nindent 4 }}
spec:
  configuration:
    - name: creds
      secret:
        name: minio-secret
  pools:
    - servers: {{ .Values.minio.statefulset.replicaCount }}
      volumesPerServer: {{ .Values.minio.statefulset.drivesPerNode }}
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.minio.persistence.size }}
          storageClassName: {{ .Values.minio.persistence.storageClass }}
      resources:
        {{- toYaml .Values.minio.resources | nindent 8 }}
  requestAutoCert: false
  exposeServices:
    console: true
    minio: true
  metrics:
    enabled: {{ .Values.minio.metrics.enabled }}
    port: 9000
{{- end }}
