apiVersion: v1
kind: Service
metadata:
  name: {{ include "dgsn-backend.fullname" . }}
  labels:
    {{- include "dgsn-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "dgsn-backend.selectorLabels" . | nindent 4 }}
