apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dgsn-frontend.fullname" . }}-env
  labels:
    {{- include "dgsn-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.nextjs.publicRuntimeConfig }}
  NEXT_PUBLIC_{{ $key | upper | replace "-" "_" }}: {{ $value | quote }}
  {{- end }}
