apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.53.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo
        - name: trace_id
          datasourceUid: jaeger

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      timeout: 60
      maxLines: 5000
      derivedFields:
        - name: traceID
          matcherRegex: "trace_id=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: tempo
        - name: jaegerTraceID
          matcherRegex: "jaeger_trace_id=(\\w+)"
          url: "$${__value.raw}"
          datasourceUid: jaeger

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service
          - component
          - k8s.pod.name
          - dgsn.operation
        mappedTags:
          - key: service.name
            value: service
        mapTagNamesEnabled: true
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - service
          - component
          - dgsn.operation
        queries:
          - query: 'rate(dgsn_api_request_duration_seconds_bucket{service="$service"}[$__rate_interval])'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      spanBar:
        type: Tag
        tag: dgsn.operation

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service
          - component
          - k8s.pod.name
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - service
          - component
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true

  - name: Grafana
    type: grafana
    access: proxy
    url: http://localhost:3000
    isDefault: false
    editable: false
